version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-cheat-sheet-rag
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hakmate-rag-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./pdf:/app/pdf
      # Mount this if you want to develop without rebuilding:
      # - .:/app

volumes:
  mongodb_data: